workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      groups:
        - keystore_group  # Secret vars: CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build

      - name: Restaurar y verificar keystore
        script: |
          # Restaurar keystore en /tmp y en la RAÍZ del repo (build.gradle lo busca ahí)
          printf "%s" "$CM_KEYSTORE" | base64 -d > /tmp/release.keystore
          printf "%s" "$CM_KEYSTORE" | base64 -d > "$CM_BUILD_DIR/release.keystore"

          echo "▶ Verificando store password..."
          keytool -list -v -keystore /tmp/release.keystore -storepass "$CM_KEYSTORE_PASSWORD" >/dev/null

          echo "▶ Verificando alias y key password..."
          keytool -list -v \
            -keystore /tmp/release.keystore \
            -storepass "$CM_KEYSTORE_PASSWORD" \
            -alias "$CM_KEY_ALIAS" \
            -keypass "$CM_KEY_PASSWORD" >/dev/null

          echo "✅ Keystore verificado correctamente."

      - name: Preparar plataforma y parchear build.gradle (reemplazar literales de firma)
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          GRADLE_FILE="platforms/android/app/build.gradle"
          if [ ! -f "$GRADLE_FILE" ]; then
            echo "❌ No se encontró $GRADLE_FILE"; exit 1
          fi

          echo "▶ Reemplazando literales 'CM_KEY_*' por valores reales (enmascarados en logs)"
          # Reemplazar 'CM_KEY_ALIAS' y "CM_KEY_ALIAS" por el alias real, preservando el tipo de comilla.
          perl -0777 -pe "s/(['\"])CM_KEY_ALIAS\\1/\$1$CM_KEY_ALIAS\$1/g" -i.bak "$GRADLE_FILE"
          # Reemplazar 'CM_KEYSTORE_PASSWORD' y "CM_KEYSTORE_PASSWORD"
          perl -0777 -pe "s/(['\"])CM_KEYSTORE_PASSWORD\\1/\$1$CM_KEYSTORE_PASSWORD\$1/g" -i.bak "$GRADLE_FILE"
          # Reemplazar 'CM_KEY_PASSWORD' y "CM_KEY_PASSWORD"
          perl -0777 -pe "s/(['\"])CM_KEY_PASSWORD\\1/\$1$CM_KEY_PASSWORD\$1/g" -i.bak "$GRADLE_FILE"

          # Asegurar que la ruta del keystore apunta al de la RAÍZ del repo
          perl -0777 -pe "s/file\\(['\\\"]release\\.keystore['\\\"]\\)/file\\('../../release.keystore'\\)/g" -i "$GRADLE_FILE"

          echo "✅ Parche aplicado en $GRADLE_FILE"

      - name: Construir APK firmado (Gradle/Cordova)
        script: |
          # Forzar APK (no AAB). El build.gradle ya contiene los datos reales de firma
          ionic cordova build android --prod --release -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
