workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      groups:
        - keystore_group  # CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build

      - name: Restaurar y verificar keystore
        script: |
          # Restaurar el keystore desde variable
          printf "%s" "$CM_KEYSTORE" | base64 -d > release.keystore

          echo "▶ Verificando store password..."
          keytool -list -v -keystore release.keystore -storepass "$CM_KEYSTORE_PASSWORD" >/dev/null

          echo "▶ Verificando alias y key password..."
          keytool -list -v \
            -keystore release.keystore \
            -storepass "$CM_KEYSTORE_PASSWORD" \
            -alias "$CM_KEY_ALIAS" \
            -keypass "$CM_KEY_PASSWORD" >/dev/null

          echo "✅ Keystore verificado correctamente."

      - name: Construir APK firmado (Gradle/Cordova)
        script: |
          ionic cordova platform rm android || true
          ionic cordova platform add android

          ionic cordova build android --prod --release -- \
            --packageType=apk \
            --keystore=release.keystore \
            --storePassword="$CM_KEYSTORE_PASSWORD" \
            --alias="$CM_KEY_ALIAS" \
            --password="$CM_KEY_PASSWORD"

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
