workflows:
  build-android-debug:
    name: Moodle App Build for Android (DEBUG - rápido para pruebas de marca)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install
          ionic build

      - name: Preparar recursos Android (icon y splash)
        script: |
          set -e
          # Validar que existe el icono
          if [ ! -f resources/icon.png ]; then
            echo "❌ No se encontró resources/icon.png"; exit 1
          fi
          # Validar que existe el splash
          if [ ! -f resources/splash.png ]; then
            echo "❌ No se encontró resources/splash.png"; exit 1
          fi

          # Crear carpetas si no existen
          mkdir -p resources/android

          # Copiar icon como backup en foreground/background
          cp resources/icon.png resources/android/icon-background.png
          cp resources/icon.png resources/android/icon-foreground.png

          echo "▶ Generando assets de splash e icon con cordova-res..."
          ionic cordova resources android --force --icon --splash
          echo "✅ Recursos Android listos."

      - name: Preparar plataforma Android (sin tocar firma)
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

      - name: Construir APK (DEBUG)
        script: |
          ionic cordova build android --debug -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
