workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      groups:
        - keystore_group  # Debe coincidir con el grupo en Codemagic donde subiste el keystore
      node: 20.18.0
      java: 17
    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build
      - name: Construir APK (unsigned)
        script: |
          # Restaurar el keystore ANTES de compilar, porque Gradle lo requiere
          echo $CM_KEYSTORE | base64 -d > release.keystore
          
          ionic cordova platform rm android || true
          ionic cordova platform add android
          ionic cordova build android --prod --release -- --packageType=apk
      - name: Firmar y alinear APK
        script: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore release.keystore \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            $CM_KEY_ALIAS

          zipalign -v 4 \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            platforms/android/app/build/outputs/apk/release/app-release.apk
    artifacts:
      - platforms/android/app/build/outputs/apk/release/app-release.apk
