workflows:
  build-android:
    name: Moodle App Build for Android (Cordova)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      node: 20.18.0
      java: 11
    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build
      - name: Construir APK
        script: |
          ionic cordova platform add android
          ionic cordova build android --prod --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk