workflows:
  build-android-debug:
    name: Moodle App Build for Android (DEBUG - pruebas de marca)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          set -e
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install
          ionic build

      - name: Validar splash (>= 2732x2732)
        script: |
          set -e
          [ -f resources/splash.png ] || { echo "❌ No se encontró resources/splash.png"; exit 1; }
          python3 -m pip install --upgrade --quiet Pillow
          python3 -c "from PIL import Image; import sys; im=Image.open('resources/splash.png'); w,h=im.size; print(f'▶ splash.png: {w}x{h}px'); 
if w>=2732 and h>=2732: sys.exit(0)
print('❌ El splash debe ser al menos 2732x2732 px (recomendado 2732x2732, centrado).', file=sys.stderr); sys.exit(2)"

      - name: Generar recursos Android (solo splash)
        script: |
          set -e
          mkdir -p resources/android
          # Si falta icon.png, crear uno mínimo para evitar warnings
          if [ ! -f resources/icon.png ]; then
            echo "ℹ️ No hay resources/icon.png; se crea uno temporal mínimo."
            echo iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII= | base64 -d > resources/icon.png
          fi
          ionic cordova resources android --force --splash
          echo "▶ Directorios drawable presentes:"
          find platforms/android/app/src/main/res -maxdepth 1 -type d -name "drawable*" | sort

      - name: Preparar plataforma Android (limpia y reañade)
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

      - name: Construir APK (DEBUG)
        script: |
          set -e
          ionic cordova build android --debug -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
