workflows:
  # ------------------------------------------------------------
  # DEBUG: APK sin firma (rápido para validar branding y estilos)
  # ------------------------------------------------------------
  build-android-debug:
    name: Moodle App Build for Android (DEBUG - splash PNG preferencia)
    max_build_duration: 60
    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
    scripts:
      - name: Instalar dependencias
        script: |
          set -e
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install

      - name: Configurar idioma por defecto (moodle.config.json)
        script: |
          set -e
          # Ajusta "languages" a ["es"] (solo español) o ["es","en"] (bilingüe)
          cat > moodle.config.json <<'JSON'
          {
            "app_id": "com.upc.moodleapp",
            "appname": "Moodle UPC",
            "versioncode": 10000,
            "versionname": "1.0.0",
            "languages": ["es","en"]
          }
          JSON
          echo "✅ moodle.config.json escrito con languages = [\"es\",\"en\"]"

      - name: Descargar/actualizar paquetes de idioma (ES) — FIX
        script: |
          set -e
          mkdir -p src/assets/lang
          HAVE_SCRIPT=false

          # 1) Script oficial si existe en package.json
          if npm run 2>/dev/null | grep -q "lang:update-langpacks"; then
            echo "▶ Ejecutando: npm run lang:update-langpacks"
            npm run lang:update-langpacks && HAVE_SCRIPT=true
          fi

          # 2) Script del repo si existe (fallback)
          if [ "$HAVE_SCRIPT" != "true" ] && [ -x scripts/update_langpacks.sh ]; then
            echo "▶ Ejecutando: scripts/update_langpacks.sh"
            bash scripts/update_langpacks.sh && HAVE_SCRIPT=true
          fi

          # 3) Último recurso: crear es.json mínimo para no romper el build
          if [ ! -f src/assets/lang/es.json ]; then
            echo "⚠️ No se obtuvo es.json automáticamente; creando base mínima…"
            cat > src/assets/lang/es.json <<'EOF'
          {
            "app.title": "Moodle UPC",
            "app.ok": "Aceptar",
            "app.cancel": "Cancelar",
            "app.back": "Atrás"
          }
          EOF
          fi

          # 4) Verificación
          if [ ! -s src/assets/lang/es.json ]; then
            echo "❌ src/assets/lang/es.json no existe o está vacío."
            exit 1
          fi
          echo "✅ Idioma ES disponible en src/assets/lang/es.json"

      - name: Limpiar cachés/artefactos para forzar assets y estilos nuevos
        script: |
          set -e
          rm -rf www platforms/android || true
          rm -rf node_modules/.cache || true
          rm -rf ~/.gradle/caches/build-cache-* || true

      - name: Compilar web (Ionic) con estilos actualizados
        script: |
          set -e
          ionic build

      - name: Preparar recursos (icon/adaptive) y plataforma
        script: |
          set -e
          [ -f resources/icon.png ] || { echo "❌ Falta resources/icon.png"; exit 1; }
          [ -f resources/android/logo.png ] || { echo "❌ Falta resources/android/logo.png"; exit 1; }
          mkdir -p resources/android
          cp resources/icon.png resources/android/icon-foreground.png
          cp resources/icon.png resources/android/icon-background.png
          ionic cordova resources android --force --icon || true

          ionic cordova platform add android
          ionic cordova clean android || true

      - name: Compilar APK (DEBUG)
        script: |
          set -e
          ionic cordova build android --debug -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk


  # -----------------------------------------------------------------
  # RELEASE: Firma con keystore y genera AAB para publicar en Play
  # Requiere en el grupo 'keystore_group':
  #  - CM_KEYSTORE (base64 del .keystore/.jks)
  #  - CM_KEYSTORE_PASSWORD
  #  - CM_KEY_ALIAS
  #  - CM_KEY_PASSWORD
  #  - GOOGLE_SERVICES_JSON_B64 (base64 del google-services.json de com.upc.moodleapp)
  # -----------------------------------------------------------------
  build-android-release:
    name: Moodle App Build for Android (RELEASE AAB firmado para Play)
    max_build_duration: 60
    environment:
      node: 20.18.0
      java: 17
      groups:
        - keystore_group
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          set -e
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install

      - name: Configurar idioma por defecto (moodle.config.json)
        script: |
          set -e
          # Ajusta "languages" a ["es"] (solo español) o ["es","en"] (bilingüe)
          cat > moodle.config.json <<'JSON'
          {
            "app_id": "com.upc.moodleapp",
            "appname": "Moodle UPC",
            "versioncode": 10000,
            "versionname": "1.0.0",
            "languages": ["es","en"]
          }
          JSON
          echo "✅ moodle.config.json escrito con languages = [\"es\",\"en\"]"

      - name: Descargar/actualizar paquetes de idioma (ES) — FIX
        script: |
          set -e
          mkdir -p src/assets/lang
          HAVE_SCRIPT=false

          # 1) Script oficial si existe en package.json
          if npm run 2>/dev/null | grep -q "lang:update-langpacks"; then
            echo "▶ Ejecutando: npm run lang:update-langpacks"
            npm run lang:update-langpacks && HAVE_SCRIPT=true
          fi

          # 2) Script del repo si existe (fallback)
          if [ "$HAVE_SCRIPT" != "true" ] && [ -x scripts/update_langpacks.sh ]; then
            echo "▶ Ejecutando: scripts/update_langpacks.sh"
            bash scripts/update_langpacks.sh && HAVE_SCRIPT=true
          fi

          # 3) Último recurso: crear es.json mínimo para no romper el build
          if [ ! -f src/assets/lang/es.json ]; then
            echo "⚠️ No se obtuvo es.json automáticamente; creando base mínima…"
            cat > src/assets/lang/es.json <<'EOF'
          {
            "app.title": "Moodle UPC",
            "app.ok": "Aceptar",
            "app.cancel": "Cancelar",
            "app.back": "Atrás"
          }
          EOF
          fi

          # 4) Verificación
          if [ ! -s src/assets/lang/es.json ]; then
            echo "❌ src/assets/lang/es.json no existe o está vacío."
            exit 1
          fi
          echo "✅ Idioma ES disponible en src/assets/lang/es.json"

      - name: Limpiar y compilar web (Ionic)
        script: |
          set -e
          rm -rf www platforms/android || true
          rm -rf node_modules/.cache || true
          ionic build

      - name: Recursos (icon/adaptive) y plataforma
        script: |
          set -e
          [ -f resources/icon.png ] || { echo "❌ Falta resources/icon.png"; exit 1; }
          mkdir -p resources/android
          cp resources/icon.png resources/android/icon-foreground.png
          cp resources/icon.png resources/android/icon-background.png
          ionic cordova resources android --force --icon || true

          ionic cordova platform add android
          ionic cordova clean android || true

      - name: Restaurar google-services.json (Firebase)
        script: |
          set -e
          if [ -z "${GOOGLE_SERVICES_JSON_B64:-}" ]; then
            echo "❌ Falta GOOGLE_SERVICES_JSON_B64 en el grupo 'keystore_group'"; exit 1
          fi

          echo "▶ Restaurando google-services.json…"
          ( printf "%s" "$GOOGLE_SERVICES_JSON_B64" | base64 --decode > /tmp/google-services.json ) || \
          ( printf "%s" "$GOOGLE_SERVICES_JSON_B64" | base64 -d        > /tmp/google-services.json ) || \
          ( printf "%s" "$GOOGLE_SERVICES_JSON_B64" | base64 -D        > /tmp/google-services.json )

          # Copiar a rutas esperadas por gradle/plugins
          mkdir -p platforms/android/app src
          cp -f /tmp/google-services.json platforms/android/app/google-services.json
          mkdir -p platforms/android/app/src/release
          cp -f /tmp/google-services.json platforms/android/app/src/release/google-services.json

          echo "▶ Validando package_name esperado ($PACKAGE_NAME)…"
          if grep -q "\"package_name\"[[:space:]]*:[[:space:]]*\"$PACKAGE_NAME\"" /tmp/google-services.json; then
            echo "✅ google-services.json contiene $PACKAGE_NAME"
          else
            echo "❌ El google-services.json no corresponde a $PACKAGE_NAME"
            echo "   Paquetes encontrados:"
            grep -o "\"package_name\"[^\"]*\"[^\"]*\"" /tmp/google-services.json | sed 's/.*"package_name":[[:space:]]*"\([^"]*\)".*/ - \1/'
            exit 1
          fi

      - name: Sanity check del keystore (valida storepass/alias/keypass y detecta JKS/PKCS12)
        script: |
          set -e
          for v in CM_KEYSTORE CM_KEYSTORE_PASSWORD CM_KEY_ALIAS CM_KEY_PASSWORD; do
            [ -n "${!v:-}" ] || { echo "❌ Falta $v en 'keystore_group'"; exit 1; }
          done

          echo "▶ Restaurando /tmp/release.keystore…"
          ( printf "%s" "$CM_KEYSTORE" | base64 --decode > /tmp/release.keystore ) || \
          ( printf "%s" "$CM_KEYSTORE" | base64 -d        > /tmp/release.keystore ) || \
          ( printf "%s" "$CM_KEYSTORE" | base64 -D        > /tmp/release.keystore )

          if [ ! -s /tmp/release.keystore ]; then
            echo "❌ Keystore vacío o corrupto"; exit 1
          fi

          echo "▶ Validando STOREPASS…"
          if ! keytool -list -v -keystore /tmp/release.keystore -storepass "$CM_KEYSTORE_PASSWORD" >/tmp/ksinfo.txt 2>/dev/null; then
            echo "❌ Store password (CM_KEYSTORE_PASSWORD) incorrecto."; exit 1
          fi

          echo "▶ Detectando tipo de keystore…"
          TYPE=$(grep -i "Keystore type:" /tmp/ksinfo.txt | awk -F': ' '{print $2}' | tr '[:upper:]' '[:lower:]')
          [ -z "$TYPE" ] && TYPE="jks"
          echo "✅ Keystore type: $TYPE"

          echo "▶ Validando ALIAS y KEYPASS…"
          if ! keytool -list -v \
            -keystore /tmp/release.keystore \
            -storepass "$CM_KEYSTORE_PASSWORD" \
            -alias "$CM_KEY_ALIAS" \
            -keypass "$CM_KEY_PASSWORD" >/dev/null 2>&1; then
            echo "❌ Alias ($CM_KEY_ALIAS) o key password (CM_KEY_PASSWORD) incorrectos."; exit 1
          fi
          echo "✅ Alias y key password válidos."

          echo "▶ Creando /tmp/build.json…"
          cat >/tmp/build.json <<'EOF'
          {
            "android": {
              "release": {
                "keystore": "/tmp/release.keystore",
                "storePassword": "<hidden>",
                "alias": "<hidden>",
                "password": "<hidden>",
                "keystoreType": "auto",
                "packageType": "bundle"
              }
            }
          }
          EOF

      - name: Build RELEASE AAB firmado
        script: |
          set -e
          # Sustituir los placeholders del build.json por variables reales sin exponerlas en logs
          sed -i.bak "s/<hidden>/$CM_KEYSTORE_PASSWORD/g" /tmp/build.json
          sed -i.bak "0,/<hidden>/s//${CM_KEY_ALIAS}/" /tmp/build.json
          sed -i.bak "0,/<hidden>/s//${CM_KEY_PASSWORD}/" /tmp/build.json
          # Detectar tipo real del keystore
          TYPE="jks"
          if keytool -list -v -keystore /tmp/release.keystore -storepass "$CM_KEYSTORE_PASSWORD" >/tmp/ksinfo2.txt 2>/dev/null; then
            TYPE=$(grep -i "Keystore type:" /tmp/ksinfo2.txt | awk -F': ' '{print $2}' | tr '[:upper:]' '[:lower:]')
            [ -z "$TYPE" ] && TYPE="jks"
          fi
          sed -i.bak "s/\"keystoreType\": \"auto\"/\"keystoreType\": \"${TYPE}\"/" /tmp/build.json

          ionic cordova build android --prod --release --buildConfig=/tmp/build.json -- --packageType=bundle

          echo "▶ Artefactos generados:"
          find platforms/android/app/build/outputs -type f | sed 's#^#  - #'

          test -f platforms/android/app/build/outputs/bundle/release/app-release.aab || { echo "❌ No se generó el AAB release"; exit 1; }

    artifacts:
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - platforms/android/app/build/outputs/**/*.apk
