workflows:
  build-android:
    name: Moodle App Build for Android (APK unsigned)
    max_build_duration: 60
    instance_type: mac_mini

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install
          ionic build

      - name: Preparar recursos Android (adaptive icon)
        script: |
          set -e
          mkdir -p resources/android
          # Si tienes resources/icon.png lo usamos; si no, generamos uno mínimo
          if [ -f resources/icon.png ]; then
            BASE=resources/icon.png
          else
            # PNG 1x1 en base64
            echo iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII= | base64 -d > resources/android/_base.png
            BASE=resources/android/_base.png
          fi

          # En macOS está disponible 'sips'
          sips -s format png -Z 1024 "$BASE" --out resources/android/icon-background.png >/dev/null
          sips -s format png -Z 1024 "$BASE" --out resources/android/icon-foreground.png >/dev/null

          # Generar resources para Android (si ya existen no falla)
          ionic cordova resources android --force || true
          echo "✅ Adaptive icon listo."

      - name: Preparar plataforma Android y desactivar firma de Gradle
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          GRADLE_FILE="platforms/android/app/build.gradle"
          if [ ! -f "$GRADLE_FILE" ]; then
            echo "❌ No se encontró $GRADLE_FILE"; exit 1
          fi

          echo "▶ Neutralizando signing en $GRADLE_FILE…"
          # Desactivar bloques y referencias de firma para que sea realmente unsigned
          sed -i.bak 's/\bsigningConfigs\b/signingConfigs_DISABLED/g' "$GRADLE_FILE" || true
          sed -i.bak 's/\bsigningConfig[[:space:]]\+signingConfigs\.release/\/\/ signing disabled/g' "$GRADLE_FILE" || true

      - name: Construir APK (unsigned)
        script: |
          ionic cordova build android --prod --release -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
