workflows:
  build-android-debug:
    name: Moodle App Build for Android (DEBUG - pruebas de marca)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install
          ionic build

      - name: Preparar recursos (icon y splash)
        script: |
          set -e
          [ -f resources/icon.png ] || { echo "❌ Falta resources/icon.png"; exit 1; }
          [ -f resources/splash.png ] || { echo "❌ Falta resources/splash.png"; exit 1; }

          # Adaptive icon requerido por cordova-res
          mkdir -p resources/android
          cp resources/icon.png resources/android/icon-foreground.png
          cp resources/icon.png resources/android/icon-background.png

          echo "▶ Generando assets con cordova-res (icon+splash)…"
          ionic cordova resources android --force --icon --splash || true
          echo "✅ cordova-res ejecutado."

      - name: Preparar plataforma Android
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          # Drawable que usará el splash del sistema (@drawable/ic_splash)
          mkdir -p platforms/android/app/src/main/res/drawable-nodpi
          cp resources/splash.png platforms/android/app/src/main/res/drawable-nodpi/ic_splash.png

          echo "▶ Verificando drawable ic_splash:"
          ls -l platforms/android/app/src/main/res/drawable-nodpi/ic_splash.png || { echo "❌ No se creó ic_splash.png"; exit 1; }

      - name: Construir APK (DEBUG)
        script: |
          ionic cordova build android --debug -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
