workflows:
  build-android:
    name: Moodle App Build for Android
    max_build_duration: 60
    instance_type: linux_x2  # Cambiado aquí
    environment:
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      node: 16.20.0
      java: 11
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
          npm install -g @ionic/cli cordova
          ionic repair
          ionic build
      - name: Construir APK
        script: |
          npx cap sync android
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk