workflows:
  android_unsigned:
    name: Moodle App • Android (unsigned)
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      node: 18.18.0
      java: 17
    scripts:
      - name: Print versions
        script: |
          node -v
          npm -v
          java -version
      - name: Install global CLIs
        script: |
          npm i -g @ionic/cli cordova
      - name: Install project deps & build web
        script: |
          npm ci
          ionic build
      - name: Prepare Android platform
        script: |
          cordova platform rm android || true
          cordova platform add android@12
          cordova requirements
      - name: Build APK (unsigned)
        script: |
          cordova build android --release --packageType=apk --verbose
    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
