workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      node: 20.18.0
      java: 17

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build
      - name: Construir APK
        script: |
          ionic cordova platform rm android || true
          ionic cordova platform add android
          ionic cordova build android --prod --release --buildConfig=build.json
    artifacts:
      - platforms/android/app/build/outputs/apk/release/app-release.apk
