workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60

    environment:
      node: 20.18.0          # Requerido por Moodle App 5.0
      java: 17               # Requerido por cordova-android 14
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      groups:
        - keystore_group     # Debe contener las 4 variables CM_* mencionadas arriba

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build

      - name: Construir APK firmado (Gradle/Cordova)
        script: |
          # Restaurar keystore ANTES del build (Gradle lo requiere)
          echo "$CM_KEYSTORE" | base64 -d > release.keystore

          # Preparar plataforma Android
          ionic cordova platform rm android || true
          ionic cordova platform add android

          # Build en modo release, forzando APK y pasando credenciales de firma
          ionic cordova build android --prod --release -- \
            --packageType=apk \
            --keystore=release.keystore \
            --storePassword="$CM_KEYSTORE_PASSWORD" \
            --alias="$CM_KEY_ALIAS" \
            --password="$CM_KEY_PASSWORD"

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk