workflows:
  build-android:
    name: Moodle App Build for Android
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      node: 20.18.0
      java: 11
    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build
      - name: Crear plataforma Android
        script: |
          npx cap add android
      - name: Construir APK
        script: |
          npx cap sync android
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
