workflows:
  android-cordova-release:
    name: Moodle App Android (Cordova, signed)
    max_build_duration: 60
    instance_type: mac_mini

    environment:
      node: 16.20.0
      java: 11
      vars:
        # Ajusta a tu id de paquete y nombre visible
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      # No es necesario definir grupos si usas Code signing de Codemagic.
      # Las variables CM_* llegan automáticamente desde Code signing.

    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches

    scripts:
      - name: Mostrar info de entorno
        script: |
          node -v
          java -version
          echo "Keystore path: $CM_KEYSTORE_PATH (debe existir si configuraste Code signing)"

      - name: Instalar herramientas
        script: |
          npm ci
          npm i -g @ionic/cli cordova

      - name: Preparar proyecto Cordova
        script: |
          ionic repair || true
          ionic build
          # Fuerza plataforma Android moderna (ajusta versión si tu proyecto lo requiere)
          cordova platform remove android || true
          cordova platform add android@12

      - name: Aumentar memoria Gradle
        script: |
          echo "org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8" >> platforms/android/gradle.properties

      - name: Configurar firma (Gradle)
        script: |
          # Usamos las variables del Code signing de Codemagic
          # Crea release-signing.properties que Gradle/cordova-android reconocen automáticamente.
          cat > platforms/android/release-signing.properties <<EOF
          storeFile=$CM_KEYSTORE_PATH
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$CM_KEY_PASSWORD
          EOF
          echo "release-signing.properties creado."

      - name: Construir APK Release firmado (Cordova)
        script: |
          # --packageType=apk para generar APK (no AAB) y que use la firma release
          cordova build android --release --packageType=apk --verbose

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk

    publishing:
      email:
        recipients:
          - "tucorreo@dominio.com"
        notify:
          success: true
          failure: true
