workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      groups:
        - keystore_group  # CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build

      - name: Restaurar keystore y crear release-signing.properties
        script: |
          # 1) Restaurar keystore en /tmp y en la RAÍZ del repo (CM_BUILD_DIR)
          printf "%s" "$CM_KEYSTORE" | base64 -d > /tmp/release.keystore
          printf "%s" "$CM_KEYSTORE" | base64 -d > "$CM_BUILD_DIR/release.keystore"

          echo "▶ Verificando store password..."
          keytool -list -v -keystore /tmp/release.keystore -storepass "$CM_KEYSTORE_PASSWORD" >/dev/null
          echo "▶ Verificando alias y key password..."
          keytool -list -v \
            -keystore /tmp/release.keystore \
            -storepass "$CM_KEYSTORE_PASSWORD" \
            -alias "$CM_KEY_ALIAS" \
            -keypass "$CM_KEY_PASSWORD" >/dev/null
          echo "✅ Keystore verificado correctamente."

          # 2) Crear el properties que usará Gradle/Cordova
          mkdir -p platforms/android
          cat > platforms/android/release-signing.properties <<EOF
          storeFile=$CM_BUILD_DIR/release.keystore
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$CM_KEY_PASSWORD
          EOF

      - name: Construir APK firmado (Gradle/Cordova)
        script: |
          ionic cordova platform rm android || true
          ionic cordova platform add android

          # Forzar APK (no AAB) y decirle a Gradle qué properties usar
          ionic cordova build android --prod --release -- \
            --packageType=apk \
            --gradleArg=-PcdvReleaseSigningPropertiesFile=platforms/android/release-signing.properties

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
