workflows:
  build-android-debug:
    name: Moodle App Build for Android (DEBUG - pruebas de marca)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install
          ionic build

      - name: Preparar recursos (icon y adaptive icon)
        script: |
          set -e
          [ -f resources/icon.png ] || { echo "❌ Falta resources/icon.png"; exit 1; }
          [ -f resources/splash.png ] || { echo "❌ Falta resources/splash.png"; exit 1; }
          [ -f resources/android/drawable/ic_splash.xml ] || { echo "❌ Falta resources/android/drawable/ic_splash.xml"; exit 1; }

          # Adaptive icon requerido por cordova-res
          mkdir -p resources/android
          cp resources/icon.png resources/android/icon-foreground.png
          cp resources/icon.png resources/android/icon-background.png

          ionic cordova resources android --force --icon || true
          echo "✅ cordova-res ejecutado."

      - name: Preparar plataforma Android y forzar splash del sistema
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          # Verificar que config.xml copió los recursos a res/
          test -f platforms/android/app/src/main/res/drawable/ic_splash.xml \
            || { echo "❌ Falta ic_splash.xml en res/drawable"; exit 1; }
          test -f platforms/android/app/src/main/res/drawable-nodpi/ic_splash_png.png \
            || { echo "❌ Falta ic_splash_png.png en res/drawable-nodpi"; exit 1; }

          MANIFEST="platforms/android/app/src/main/AndroidManifest.xml"
          echo "▶ Verificando AndroidManifest.xml…"
          if ! grep -q 'windowSplashScreenAnimatedIcon' "$MANIFEST"; then
            echo "⚠️  Manifest sin atributo; aplicando patch con perl…"
            perl -0777 -i -pe 's/<application\b/<application android:windowSplashScreenAnimatedIcon="@drawable\/ic_splash" android:windowSplashScreenBackground="#FFFFFF" android:windowSplashScreenIconBackgroundColor="#FFFFFF" /s if $_ !~ /windowSplashScreenAnimatedIcon=/' "$MANIFEST"
          fi

          # Confirmación
          grep -n 'windowSplashScreenAnimatedIcon' "$MANIFEST" \
            || { echo "❌ Patch no aplicado"; exit 1; }
          grep -n '@drawable/ic_splash' "$MANIFEST" \
            || { echo "❌ Manifest no apunta a @drawable/ic_splash"; exit 1; }

      - name: Compilar APK (DEBUG)
        script: |
          ionic cordova build android --debug -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
