workflows:
  build-android:
    name: Moodle App Build for Android (APK unsigned)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp cordova-res
          npm ci || npm install
          ionic build

      - name: Preparar plataforma Android y desactivar firma de Gradle
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          GRADLE_FILE="platforms/android/app/build.gradle"
          if [ ! -f "$GRADLE_FILE" ]; then
            echo "❌ No se encontró $GRADLE_FILE"; exit 1
          fi

          echo "▶ Neutralizando signing en $GRADLE_FILE…"
          sed -i.bak 's/\bsigningConfigs\b/signingConfigs_DISABLED/g' "$GRADLE_FILE" || true
          sed -i.bak 's/\bsigningConfig[[:space:]]\+signingConfigs\.release/\/\/ signing disabled/g' "$GRADLE_FILE" || true

      - name: Construir APK (unsigned)
        script: |
          ionic cordova build android --prod --release -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
