workflows:
  build-android-debug:
    name: Moodle App Build for Android (DEBUG - rápido para pruebas de marca)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova cordova-res gulp
          npm ci || npm install
          ionic build

      - name: Preparar recursos Android (icon y splash para cordova-res)
        script: |
          set -e
          if [ ! -f resources/icon.png ]; then
            echo "❌ Falta resources/icon.png"; exit 1
          fi
          if [ ! -f resources/splash.png ]; then
            echo "❌ Falta resources/splash.png"; exit 1
          fi
          ionic cordova resources android --force --icon --splash || true
          echo "✅ cordova-res ejecutado."

      - name: Preparar plataforma Android
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          # Crear el drawable que usará el splash del sistema (@drawable/ic_splash)
          mkdir -p platforms/android/app/src/main/res/drawable-nodpi
          cp resources/splash.png platforms/android/app/src/main/res/drawable-nodpi/ic_splash.png

          echo "▶ Comprobando que exista el drawable:"
          ls -l platforms/android/app/src/main/res/drawable-nodpi/ic_splash.png

      - name: Construir APK (DEBUG)
        script: |
          ionic cordova build android --debug -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
