workflows:
  build-android:
    name: Moodle App Build for Android (APK unsigned)
    max_build_duration: 60

    environment:
      node: 20.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp cordova-res
          npm ci || npm install
          ionic build

      - name: Preparar recursos Android (adaptive icon)
        script: |
          set -e
          mkdir -p resources/android
          if [ -f resources/icon.png ]; then
            cp resources/icon.png resources/android/icon-background.png
            cp resources/icon.png resources/android/icon-foreground.png
          else
            echo iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII= | base64 -d > resources/android/icon-background.png
            cp resources/android/icon-background.png resources/android/icon-foreground.png
          fi
          ionic cordova resources android --force || true
          echo "✅ Adaptive icon OK."

      - name: Preparar plataforma Android y DESACTIVAR por completo la firma
        script: |
          set -e
          ionic cordova platform rm android || true
          ionic cordova platform add android

          # 1) Eliminar archivos/props que activan firma
          rm -f release-signing.properties || true
          rm -f android/release-signing.properties || true
          rm -f platforms/android/release-signing.properties || true
          # Algunas plantillas usan estas variables en gradle.properties:
          sed -i.bak '/STORE_FILE/d;/STORE_PASSWORD/d;/KEY_ALIAS/d;/KEY_PASSWORD/d' platforms/android/gradle.properties || true
          sed -i.bak '/STORE_FILE/d;/STORE_PASSWORD/d;/KEY_ALIAS/d;/KEY_PASSWORD/d' gradle.properties || true

          # 2) Comentar llamadas de firma dentro de app/build.gradle
          GRADLE_FILE="platforms/android/app/build.gradle"
          if [ ! -f "$GRADLE_FILE" ]; then
            echo "❌ No se encontró $GRADLE_FILE"; exit 1
          fi

          echo "▶ Neutralizando signing en $GRADLE_FILE…"
          # Evita que el bloque se referencie
          sed -i.bak 's/\bsigningConfig[[:space:]]\+signingConfigs\.release/\/\/ signing disabled/g' "$GRADLE_FILE" || true
          # Comentar líneas típicas de firma (independiente del bloque donde estén)
          sed -i.bak -e 's/^\([[:space:]]*storeFile[[:space:]].*\)$/\/\/ \1/' \
                      -e 's/^\([[:space:]]*storePassword[[:space:]].*\)$/\/\/ \1/' \
                      -e 's/^\([[:space:]]*keyAlias[[:space:]].*\)$/\/\/ \1/' \
                      -e 's/^\([[:space:]]*keyPassword[[:space:]].*\)$/\/\/ \1/' "$GRADLE_FILE" || true
          # Por si aparece ruta explícita a release.keystore, coméntala
          sed -i.bak 's/^\(.*release\.keystore.*\)$/\/\/ \1/' "$GRADLE_FILE" || true

          echo "▶ Comprobando referencias residuales a keystore…"
          (grep -RIn "keystore|signingConfig|release\\.keystore" platforms/android/app || true) | head -n 100

      - name: Construir APK (unsigned)
        script: |
          # Forzamos APK de release pero sin firma (ya neutralizada en Gradle)
          ionic cordova build android --prod --release -- --packageType=apk

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
