workflows:
  build-android:
    name: Moodle App Build for Android (.apk)
    max_build_duration: 60

    environment:
      node: 20.18.0          # Requerido por Moodle App 5.0
      java: 17               # Requerido por cordova-android 14
      vars:
        PACKAGE_NAME: "com.upc.moodleapp"
        APP_NAME: "Moodle UPC"
      groups:
        - keystore_group     # Debe contener: CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD

    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g @ionic/cli cordova gulp
          npm ci || npm install
          ionic build

      - name: Construir APK (unsigned)
        script: |
          ionic cordova platform rm android || true
          ionic cordova platform add android
          # Forzar APK (no AAB)
          ionic cordova build android --prod --release -- --packageType=apk

      - name: Firmar y alinear APK
        script: |
          # Restaurar keystore desde variable (base64)
          echo $CM_KEYSTORE | base64 -d > release.keystore

          # Firmar APK no firmado
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore release.keystore \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            $CM_KEY_ALIAS

          # Alinear y dejar como final
          zipalign -v 4 \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            platforms/android/app/build/outputs/apk/release/app-release.apk

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
